[project]
name = "guardrail"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]~=0.122.0",
    "openai~=2.8.0",
    "redis~=7.1.0",
]